-- SAP MaxDB - token FCM untuk semua user (driver/karyawan/admin/hr/hd)
CREATE TABLE DMS_USER_FCM_TOKEN (
  ID INTEGER NOT NULL DEFAULT SERIAL,
  USERNAME VARCHAR(64) NOT NULL,
  LOGINNAME VARCHAR(64),
  TOKEN LONG VARCHAR NOT NULL,
  PLATFORM VARCHAR(20) DEFAULT 'android',
  IS_ACTIVE CHAR(1) DEFAULT '1',
  UPDATED_AT TIMESTAMP NOT NULL,
  PRIMARY KEY (ID)
);

CREATE INDEX IDX_DMS_USER_FCM_TOKEN_USER ON DMS_USER_FCM_TOKEN (USERNAME, IS_ACTIVE);

