-- SAP MaxDB: tabel aduan + notifikasi staf (HR/HD/ADMIN).
-- Jalankan di MaxDB; sesuaikan tipe/serial jika rilis server Anda beda.
-- Lihat https://maxdb.sap.com/ untuk sintaks rilis spesifik.

-- Aduan pengguna (DRIVER: submitter_drvid, KARYAWAN: submitter_kryid; salah satu saja terisi)
CREATE TABLE DMS_ADUAN (
  ID INTEGER NOT NULL DEFAULT SERIAL,
  SUBMITTER_DRVID VARCHAR(64),
  SUBMITTER_KRYID VARCHAR(64),
  SUBMITTER_USERNAME VARCHAR(64) NOT NULL,
  SUBMITTER_LOGINNAME VARCHAR(64),
  PESAN LONG VARCHAR,
  STATUS VARCHAR(16) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  CLOSED_AT TIMESTAMP,
  CLOSED_BY_USERNAME VARCHAR(64),
  PRIMARY KEY (ID)
);

CREATE INDEX IDX_DMS_ADUAN_STATUS ON DMS_ADUAN (STATUS);
CREATE INDEX IDX_DMS_ADUAN_CREATED ON DMS_ADUAN (CREATED_AT);

-- Pemberitahuan per user staf; isi saat aduan OPEN baru
CREATE TABLE DMS_ADUAN_NOTIF (
  ID INTEGER NOT NULL DEFAULT SERIAL,
  ADUAN_ID INTEGER NOT NULL,
  TARGET_USERNAME VARCHAR(64) NOT NULL,
  IS_READ CHAR(1) DEFAULT '0',
  CREATED_AT TIMESTAMP NOT NULL,
  PRIMARY KEY (ID)
);

CREATE INDEX IDX_ADUAN_NOTIF_USER ON DMS_ADUAN_NOTIF (TARGET_USERNAME, IS_READ);
CREATE INDEX IDX_ADUAN_NOTIF_ADUAN ON DMS_ADUAN_NOTIF (ADUAN_ID);

-- Daftar user staf (HR/HD/ADMIN) yang menerima notif aduan; isi manual atau sync dari tabel karyawan Anda.
CREATE TABLE DMS_ADUAN_STAFF_NOTIFY (
  USERNAME VARCHAR(64) NOT NULL,
  PRIMARY KEY (USERNAME)
);
